### ISSUE TITLE
Update local Flare bots to head of main branch

### ISSUE THREAD

**Issue by rouzwelt** [rainlanguage/rain.dex.solve#8]
@thedavidmeister @hardyjosh 
update the Flare bots to head of main branch, and change the `ARB` env to the following address:
0x5E5F2Af1e7f8bC1BaF051a6c9F5e22F4C6a69C45

**Comment by hardyjosh** [comment]
I've done this

**Comment by hardyjosh** [comment]
@thedavidmeister has also done it
